### ISSUE TITLE
Use profile pattern to manage different packages login config

### ISSUE THREAD

**Issue by asika32764** [lyrasoft/warder#29]
``` yaml
profiles:
    main:
        login_name: email
    admin:
        login_name: username

packages:
    admin: admin
    front: main
```
