### ISSUE TITLE
Every package use different warder instance and config

### ISSUE THREAD

**Issue by asika32764** [lyrasoft/warder#43]
Extends https://github.com/lyrasoft/warder/issues/29

``` yaml
profiles:
    admin:
        login_name: username
        social_login: false
        admin: true
        registrable: false
        self_editable: true
        forgete_password: true
    front:
        login_name: email
        social_login: true
        admin: false
        registrable: true
        self_editable: true
        forgete_password: true

packages:
    admin: admin
    main: frontend
```
